name: dharmesh_portfollio
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  flutter_svg: ^2.2.1
  url_launcher: ^6.3.2
  toastification: ^3.0.3
  animate_do: ^4.2.0
  lottie: ^3.1.1

  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  flutter_animate: ^4.5.2
  animated_text_kit: ^4.2.3

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/resume/
    - assets/animation/

  fonts:
    - family: BoldFontMontserrat
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: MediumFontMontserrat
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: RegularFontMontserrat
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: SemiBoldFontMontserrat
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: italicFontMontserrat
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf