// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYLL8o1jEMwx7Ab1DWYBs46XULmmfTkaw',
    appId: '1:734385597166:web:138cdcd42ac73ac05361ff',
    messagingSenderId: '734385597166',
    projectId: 'dharmesh-portfollio-web-fdf8c',
    authDomain: 'dharmesh-portfollio-web-fdf8c.firebaseapp.com',
    storageBucket: 'dharmesh-portfollio-web-fdf8c.firebasestorage.app',
    measurementId: 'G-3GJ5FFPJW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8dfoA2buErqBSWIxVgfsZ-5OHNUoYCJM',
    appId: '1:734385597166:android:03317f79cfdf57945361ff',
    messagingSenderId: '734385597166',
    projectId: 'dharmesh-portfollio-web-fdf8c',
    storageBucket: 'dharmesh-portfollio-web-fdf8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmS1z1s5S-lkXHKgXkTNyVegu5A8OI4ME',
    appId: '1:734385597166:ios:1d79c319b090e5d75361ff',
    messagingSenderId: '734385597166',
    projectId: 'dharmesh-portfollio-web-fdf8c',
    storageBucket: 'dharmesh-portfollio-web-fdf8c.firebasestorage.app',
    iosBundleId: 'com.example.vikramPortfollioDark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYLL8o1jEMwx7Ab1DWYBs46XULmmfTkaw',
    appId: '1:734385597166:web:43fb94b4c04971f55361ff',
    messagingSenderId: '734385597166',
    projectId: 'dharmesh-portfollio-web-fdf8c',
    authDomain: 'dharmesh-portfollio-web-fdf8c.firebaseapp.com',
    storageBucket: 'dharmesh-portfollio-web-fdf8c.firebasestorage.app',
    measurementId: 'G-VP91RQQ6RL',
  );
}
